### ISSUE TITLE
Add HyperlinkListener for the SeerHelpDialog

### ISSUE THREAD

**Issue by kirbykn** [imsweb/seerutils-gui#4]
In SEER*Edits, we added extra logic to add a HyperlinkListener to be able to open a link in a browser from the help dialog.
The SeerHelpDialog does have an option for opening a link in the same help dialog, but not in a browser. Fabian suggested opening the link in a browser if it starts with 'http', and in the window otherwise. I think that makes sense and wouldn't have a bad side effect.

```
_pane.addHyperlinkListener(e ->
            if (e.getEventType() == EventType.ACTIVATED) {
                try {
                    if (Desktop.isDesktopSupported() && Desktop.getDesktop().isSupported(Action.BROWSE))
                        Desktop.getDesktop().browse(e.getURL().toURI());
                }
                catch (IOException | URISyntaxException ex) {
                    // ignore exception
                }
            }
        });
```

**Comment by depryf** [comment]
@kirbykn this is done.

I just did a release an hour ago, and missed this issue. So it will go with the next release, sorry about that.

On a side note, the behavior is a bit weird because clicking on a undecorated help dialog brings up the decorated version; and so clicking on a web link will do both: it will bring up the decorated version and open the browser. It's not great, but it's not worth any effort fixing.

Also, if an application doesn't want to allow the browsing (maybe it doesn't control the content of the help dialog), it can disable the functionality by removing the hyperlink listener after creating the dialog.
